### ISSUE TITLE
Build to Magic Leap 2 does not have permission to run

### ISSUE THREAD

**Issue by TadDiDio** [asus4/onnxruntime-unity#18]
**Environment (please complete the following information):**
 - OS/OS Version: Lumin OS 1.6.0
 - Source Version: main/v0.1.2
 - Unity Version: Unity 2023.3.19f1

**Describe the bug**
When building to the magic leap 2 AR headset Android device, some part of the app does not have the permissions it needs to execute. In the android logcat terminal I see the following warning repeatedly. It happens about once per second and the YoloX sample scene from the start repository runs at 3FPS without the ability to update the screen.
`Warn UnityGfxDeviceW type=1400 audit(0.0:55083): avc: denied { search } for name="traces" dev="nvme0n1p37" ino=7979011 scontext=u:r:untrusted_app:s0:c115,c256,c512,c768 tcontext=u:object_r:trace_data_file:s0 tclass=dir permissive=0
`

**Additional context**
I tried removing all the virtual texture code because magic leap 2 has platform specific methods for connecting to cameras and granting permissions. I also tried just feeding in a Texture2D instead of using a live camera but both of these attempts resulted in the same warning.

**Comment by asus4** [comment]
Hi, @TadDiDio. Thanks for trying this repository out. 

The `onnxruntime-android.aar` library looks to support the Android x86_64 platform. However, I don't have the Magic Leap 2 or other repro environment devices.

Can you share the complete ADB logcat log here? It might help to identify the issue.

**Comment by TadDiDio** [comment]
Hi, sorry for the delayed response. 

After a closer look at the output log, it seems that the warning I mentioned is not actually an issue, but instead that the model I am using has unsupported operators. The error only occurs when selecting the platform GPU provider and, in my case, NNAPI is enabled as expected. I think I just need to train a model that is fully supported.
