### ISSUE TITLE
[Info Request] : What is the difference between onnxruntime-unity and sentis

### ISSUE THREAD

**Issue by rawatsaurabh** [asus4/onnxruntime-unity#19]
Hello, 
I am just exploring the frameworks of integrating the ML/DL NN models to Unity framework. I found barracuda and then its latest migration (sentis - which is still in beta and hope to release  by end of 2024) .Sentis also provides the yolo model integration.
What benefit does onnx runtime has over sentis?
Are the examples portable on Android or iOS?
Regards,
Saurabh

**Comment by asus4** [comment]
@rawatsaurabh Thanks for your interest.

Yes, this example should work on Android and iOS. Please take a look at [my Medium post](https://medium.com/@asus4/onnx-runtime-on-unity-a40b3416529f) about why I started exploring ONNX Runtime within Unity.


In short
- Use Sentis if:
  - Targeting Web Player
  - Your model is compatible with Sentis, and the performance is good enough
- Use ONNX Runtime if:
  - Your ONNX model is not compatible with Sentis. This library is a thin wrapper of C# ONNX Runtime. It will support various models.


Other candidates:

- [TensorFlow Lite for Unity](https://github.com/asus4/tf-lite-unity-sample): my other library. I still like TensorFlow Lite. It's quite performant :)
- [NatML](https://www.natml.ai/)
- [OpenCV for Unity](https://enoxsoftware.com/opencvforunity/)
- [Ailia Unity SDK](https://axinc.jp/en/solutions/ailia_sdk.html)

Please let me know if you found other good ML libraries.

**Comment by rawatsaurabh** [comment]
Also does it work on the real time inference (of a camera) on Android/iOS? I have seen Sentis has very bad performance so far.(too slow)

**Comment by asus4** [comment]
@rawatsaurabh  You can try it yourself with this repository :)

https://github.com/asus4/onnxruntime-unity-examples
