### ISSUE TITLE
onnxruntime-extensions android aar missing in npmjs.org

### ISSUE THREAD

**Issue by SetoKaiba** [asus4/onnxruntime-unity#25]
**Environment (please complete the following information):**
 - OS/OS Version: [e.g. iOS 11.0/Andoroid 8.1/macOS 10.15.6]
 - Source Version: [e.g. master/v2.2.0]
 - Unity Version: [e.g. Unity 2019.4.5.f1]

**Describe the bug**
onnxruntime-extensions android aar missing in npmjs.org

**To Reproduce**
1. Go to 'https://www.npmjs.com/package/com.github.asus4.onnxruntime-extensions?activeTab=code'
2. Click on 'Plugins.'
3. Click on 'Android'
4. Click on 'onnxruntime-extensions-android.aar;
5. Check the content

**Expected behavior**
Android aar should not be missing

**Screenshots**

**Additional context**
Add any other context about the problem and error logs here.

**Comment by asus4** [comment]
Thank you @SetoKaiba, Confirmed the GitHub Action is failing. I will fix it.

**Comment by asus4** [comment]
We are copying the Android binary from [maven2](https://repo1.maven.org/maven2/com/microsoft/onnxruntime/onnxruntime-extensions-android/) and confirmed that some versions are missing.  In the latest version, ORT-Extensions `v0.12.4` is for Android.
