### ISSUE TITLE
Exception 0xc0000005 when testing on mini PC

### ISSUE THREAD

**Issue by khalil-i19** [asus4/onnxruntime-unity#28]
I encountered an application crash when the application was just being started on a mini PC. From crash.dmp, it throws exception 0xc0000005: The thread tried to read from or write to a virtual address for which it does not have the appropriate access. I have browsed Unity forums and other discussions related to this exception on ONNX Runtime, but I didn't find any solution to this error. 

Below is the crash log and stack trace from Player.log file

Crash!!!
SymInit: Symbol-SearchPath: '.;D:\ObjectDetectionTest_Data/Plugins\x86_64;D:/ObjectDetectionTest_Data/Plugins;D:\;C:\Windows;C:\Windows\system32;', symOptions: 534, UserName: 'USER'
OS-Version: 10.0.0
D:\ObjectDetectionTest.exe:ObjectDetectionTest.exe (00007FF6442F0000), size: 688128 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 2022.3.11.584
C:\Windows\SYSTEM32\ntdll.dll:ntdll.dll (00007FF81AD70000), size: 2191360 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3733
C:\Windows\System32\KERNEL32.DLL:KERNEL32.DLL (00007FF818EF0000), size: 802816 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3672
C:\Windows\System32\KERNELBASE.dll:KERNELBASE.dll (00007FF818700000), size: 3854336 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3810
D:\Video\UnityPlayer.dll:UnityPlayer.dll (00007FFFC1D90000), size: 31649792 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 2022.3.11.584
C:\Windows\System32\USER32.dll:USER32.dll (00007FF818D40000), size: 1761280 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3810
C:\Windows\System32\win32u.dll:win32u.dll (00007FF818190000), size: 155648 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3810
C:\Windows\System32\GDI32.dll:GDI32.dll (00007FF81AAD0000), size: 167936 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3672
C:\Windows\System32\gdi32full.dll:gdi32full.dll (00007FF818380000), size: 1150976 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3672
C:\Windows\System32\msvcp_win.dll:msvcp_win.dll (00007FF8181C0000), size: 630784 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3374
C:\Windows\System32\ucrtbase.dll:ucrtbase.dll (00007FF818260000), size: 1118208 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3593
C:\Windows\System32\ole32.dll:ole32.dll (00007FF819FE0000), size: 1724416 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3810
C:\Windows\System32\combase.dll:combase.dll (00007FF81A190000), size: 3702784 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3672
C:\Windows\System32\RPCRT4.dll:RPCRT4.dll (00007FF81AB50000), size: 1130496 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3810
C:\Windows\System32\SHLWAPI.dll:SHLWAPI.dll (00007FF819090000), size: 385024 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3672
C:\Windows\System32\msvcrt.dll:msvcrt.dll (00007FF81A8A0000), size: 684032 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 7.0.22621.2506
C:\Windows\SYSTEM32\VERSION.dll:VERSION.dll (00007FF810650000), size: 40960 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.1
C:\Windows\System32\SETUPAPI.dll:SETUPAPI.dll (00007FF8190F0000), size: 4669440 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.2506
C:\Windows\System32\ADVAPI32.dll:ADVAPI32.dll (00007FF81A520000), size: 729088 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3810
C:\Windows\System32\sechost.dll:sechost.dll (00007FF818AB0000), size: 692224 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3810
C:\Windows\System32\bcrypt.dll:bcrypt.dll (00007FF818160000), size: 163840 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.2506
C:\Windows\System32\SHELL32.dll:SHELL32.dll (00007FF819770000), size: 8777728 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3810
C:\Windows\System32\OLEAUT32.dll:OLEAUT32.dll (00007FF819570000), size: 880640 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3672
C:\Windows\System32\IMM32.dll:IMM32.dll (00007FF81AB10000), size: 200704 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3374
C:\Windows\System32\CRYPT32.dll:CRYPT32.dll (00007FF8184A0000), size: 1470464 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3810
C:\Windows\SYSTEM32\WINMM.dll:WINMM.dll (00007FF80B3B0000), size: 212992 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3672
C:\Windows\SYSTEM32\OPENGL32.dll:OPENGL32.dll (00007FFFF4400000), size: 1048576 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3672
C:\Windows\System32\WS2_32.dll:WS2_32.dll (00007FF81A950000), size: 462848 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.1
C:\Windows\SYSTEM32\WINHTTP.dll:WINHTTP.dll (00007FF814870000), size: 1269760 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3672
C:\Windows\SYSTEM32\HID.DLL:HID.DLL (00007FF816900000), size: 57344 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.1
C:\Windows\SYSTEM32\dwmapi.dll:dwmapi.dll (00007FF8152E0000), size: 176128 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3672
C:\Windows\SYSTEM32\GLU32.dll:GLU32.dll (00007FFFF43D0000), size: 184320 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.2506
C:\Windows\SYSTEM32\dxcore.dll:dxcore.dll (00007FF815350000), size: 233472 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3672
C:\Windows\system32\apphelp.dll:apphelp.dll (00007FF813DF0000), size: 618496 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3810
C:\Windows\SYSTEM32\kernel.appcore.dll:kernel.appcore.dll (00007FF8171C0000), size: 98304 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.2715
C:\Windows\System32\bcryptPrimitives.dll:bcryptPrimitives.dll (00007FF818680000), size: 503808 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3672
C:\Windows\system32\uxtheme.dll:uxtheme.dll (00007FF815060000), size: 716800 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3810
C:\Windows\System32\shcore.dll:shcore.dll (00007FF81A7A0000), size: 999424 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3810
C:\Windows\SYSTEM32\windows.storage.dll:windows.storage.dll (00007FF816000000), size: 9420800 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3810
C:\Windows\SYSTEM32\wintypes.dll:wintypes.dll (00007FF815EC0000), size: 1306624 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3810
C:\Windows\SYSTEM32\profapi.dll:profapi.dll (00007FF817FD0000), size: 135168 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3527
D:\Video\MonoBleedingEdge\EmbedRuntime\mono-2.0-bdwgc.dll:mono-2.0-bdwgc.dll (00007FFFC1330000), size: 10825728 (result: 0), SymType: '-deferred-', PDB: ''
C:\Windows\SYSTEM32\iphlpapi.dll:iphlpapi.dll (00007FF816B50000), size: 184320 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.1
D:\Video\MP14 - Naval Interactive Wall_Data\Plugins\x86_64\opencvforunity.dll:opencvforunity.dll (00007FFFBDB10000), size: 58822656 (result: 0), SymType: '-deferred-', PDB: ''
C:\Windows\SYSTEM32\MFPlat.DLL:MFPlat.DLL (00007FF8040B0000), size: 1892352 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3672
C:\Windows\SYSTEM32\MF.dll:MF.dll (00007FF801140000), size: 565248 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3810
C:\Windows\SYSTEM32\dxgi.dll:dxgi.dll (00007FF8151D0000), size: 1011712 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3672
C:\Windows\SYSTEM32\MFReadWrite.dll:MFReadWrite.dll (00007FFFCA830000), size: 1179648 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3527
C:\Windows\SYSTEM32\d3d11.dll:d3d11.dll (00007FF812F80000), size: 2453504 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3672
C:\Windows\SYSTEM32\cfgmgr32.dll:cfgmgr32.dll (00007FF817D80000), size: 319488 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.2506
C:\Windows\SYSTEM32\MFCORE.DLL:MFCORE.DLL (00007FF800C30000), size: 3772416 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3810
C:\Windows\SYSTEM32\RTWorkQ.DLL:RTWorkQ.DLL (00007FF804050000), size: 208896 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.1
C:\Windows\System32\MSCTF.dll:MSCTF.dll (00007FF818BE0000), size: 1388544 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3810
C:\Windows\SYSTEM32\directxdatabasehelper.dll:directxdatabasehelper.dll (00007FF811AE0000), size: 299008 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3672
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_cfd61829264f1746\igd10iumd64.dll:igd10iumd64.dll (00007FF80D520000), size: 4698112 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 31.0.101.4146
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_cfd61829264f1746\igd10um64xe.DLL:igd10um64xe.DLL (00007FF80BA30000), size: 25833472 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 31.0.101.4146
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_cfd61829264f1746\IntelControlLib.dll:IntelControlLib.dll (00007FF80A8A0000), size: 503808 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 1.0.134.0
C:\Windows\SYSTEM32\DEVOBJ.dll:DEVOBJ.dll (00007FF817D50000), size: 180224 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.2506
C:\Windows\System32\WINTRUST.dll:WINTRUST.dll (00007FF818610000), size: 438272 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3810
C:\Windows\SYSTEM32\MSASN1.dll:MSASN1.dll (00007FF8178F0000), size: 73728 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.2506
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_cfd61829264f1746\igdgmm64.dll:igdgmm64.dll (00007FF80A480000), size: 4288512 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 31.0.101.4146
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_cfd61829264f1746\igc64.dll:igc64.dll (00007FF805CB0000), size: 73158656 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 31.0.101.4146
C:\Windows\System32\clbcatq.dll:clbcatq.dll (00007FF818FC0000), size: 720896 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 2001.12.10941.16384
C:\Windows\system32\wbem\wbemprox.dll:wbemprox.dll (00007FFFF0850000), size: 65536 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3672
C:\Windows\SYSTEM32\wbemcomn.dll:wbemcomn.dll (00007FFFFCCD0000), size: 524288 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.2506
C:\Windows\system32\wbem\wbemsvc.dll:wbemsvc.dll (00007FFFF56E0000), size: 81920 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3672
C:\Windows\system32\wbem\fastprox.dll:fastprox.dll (00007FFFF5700000), size: 1015808 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3672
C:\Windows\SYSTEM32\amsi.dll:amsi.dll (00007FFFF3D30000), size: 118784 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3527
C:\Windows\SYSTEM32\USERENV.dll:USERENV.dll (00007FF817730000), size: 163840 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3527
C:\ProgramData\Microsoft\Windows Defender\Platform\4.18.24050.7-0\MpOav.dll:MpOav.dll (00007FFFF3760000), size: 528384 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 4.18.24050.7
C:\Windows\System32\MMDevApi.dll:MMDevApi.dll (00007FF80EC20000), size: 643072 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3672
C:\Windows\SYSTEM32\AUDIOSES.DLL:AUDIOSES.DLL (00007FFFFB210000), size: 2015232 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3810
C:\Windows\SYSTEM32\resourcepolicyclient.dll:resourcepolicyclient.dll (00007FF815880000), size: 86016 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3527
C:\Windows\SYSTEM32\powrprof.dll:powrprof.dll (00007FF816F30000), size: 315392 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3374
C:\Windows\SYSTEM32\UMPDC.dll:UMPDC.dll (00007FF816F10000), size: 77824 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.1
D:\Video\MP14 - Naval Interactive Wall_Data\Plugins\x86_64\lib_burst_generated.dll:lib_burst_generated.dll (00007FFFE27D0000), size: 253952 (result: 0), SymType: '-deferred-', PDB: ''
C:\Windows\SYSTEM32\xinput1_3.dll:xinput1_3.dll (0000000000400000), size: 122880 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 9.18.944.0
C:\Windows\SYSTEM32\dcomp.dll:dcomp.dll (00007FF8131E0000), size: 2437120 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3810
C:\Windows\SYSTEM32\textinputframework.dll:textinputframework.dll (00007FF8051D0000), size: 1368064 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3810
C:\Windows\System32\devenum.dll:devenum.dll (00007FFFCD810000), size: 135168 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3527
C:\Windows\SYSTEM32\ntmarta.dll:ntmarta.dll (00007FF8171E0000), size: 212992 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.1
C:\Windows\SYSTEM32\msdmo.dll:msdmo.dll (00007FFFFCDA0000), size: 45056 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.1
C:\Windows\SYSTEM32\onnxruntime.DLL:onnxruntime.DLL (00007FFFBCE30000), size: 7671808 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 1.10.2201.2623
C:\Windows\SYSTEM32\dbghelp.dll:dbghelp.dll (00007FF815C40000), size: 2301952 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3593
C:\Windows\SYSTEM32\SspiCli.dll:SspiCli.dll (00007FF817420000), size: 274432 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.22621.3810

========== OUTPUTTING STACK TRACE ==================

0x00007FFFC182C01C (mono-2.0-bdwgc) mono_breakpoint_clean_code
0x000002AA4D6D73F8 (Mono JIT Code) (wrapper managed-to-native) System.Buffer:InternalMemcpy (byte*,byte*,int)
0x000002AA4D6D5723 (Mono JIT Code) System.Buffer:Memcpy (byte*,byte*,int)
0x000002AA4D6D6673 (Mono JIT Code) string:memcpy (byte*,byte*,int)
0x000002AC0A1700AB (Mono JIT Code) Microsoft.ML.OnnxRuntime.NativeMethods:.cctor ()
0x000002AC0919E265 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void (object,intptr,intptr,intptr)
0x00007FFFC15C4B6E (mono-2.0-bdwgc) mono_jit_set_domain
0x00007FFFC14FD204 (mono-2.0-bdwgc) mono_object_get_virtual_method
0x00007FFFC14F7FA9 (mono-2.0-bdwgc) mono_runtime_class_init
0x00007FFFC16509C9 (mono-2.0-bdwgc) mono_set_break_policy
0x000002AA4D6D2C0B (Mono JIT Code) (wrapper managed-to-native) object:__icall_wrapper_mono_generic_class_init (intptr)
0x000002AC0919E03B (Mono JIT Code) Microsoft.ML.OnnxRuntime.SessionOptions:.ctor ()
0x000002AC0919D53B (Mono JIT Code) Microsoft.ML.OnnxRuntime.Unity.ImageInference`1<single>:.ctor (byte[],Microsoft.ML.OnnxRuntime.Unity.ImageInferenceOptions)
0x000002AC0919D1BB (Mono JIT Code) Microsoft.ML.OnnxRuntime.Examples.Yolox:.ctor (byte[],Microsoft.ML.OnnxRuntime.Examples.Yolox/Options)
0x000002AC0919CE13 (Mono JIT Code) YoloxSample:Start ()
0x000002AB7D0A3018 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
0x00007FFFC15C4B6E (mono-2.0-bdwgc) mono_jit_set_domain
0x00007FFFC14FD204 (mono-2.0-bdwgc) mono_object_get_virtual_method
0x00007FFFC14FD37C (mono-2.0-bdwgc) mono_runtime_invoke
0x00007FFFC250C8DA (UnityPlayer) ScriptingInvocation::Invoke
0x00007FFFC24FACCB (UnityPlayer) MonoBehaviour::InvokeMethodOrCoroutineChecked
0x00007FFFC24FB526 (UnityPlayer) MonoBehaviour::InvokeMethodOrCoroutineChecked
0x00007FFFC24FC72A (UnityPlayer) MonoBehaviour::DelayedStartCall
0x00007FFFC21D0FCD (UnityPlayer) DelayedCallManager::Update
0x00007FFFC233D777 (UnityPlayer) ExecutePlayerLoop
0x00007FFFC233D94F (UnityPlayer) ExecutePlayerLoop
0x00007FFFC233DD83 (UnityPlayer) PlayerLoop
0x00007FFFC258BEAB (UnityPlayer) PerformMainLoop
0x00007FFFC258E54B (UnityPlayer) MainMessageLoop
0x00007FFFC25918EB (UnityPlayer) UnityMainImpl
0x00007FFFC2591B8B (UnityPlayer) UnityMain
0x00007FF6442F11F2 (ObjectDetectionTest) __scrt_common_main_seh
0x00007FF818F0257D (KERNEL32) BaseThreadInitThunk
0x00007FF81ADCAF28 (ntdll) RtlUserThreadStart

========== END OF STACKTRACE ===========

Device Specification:
- OS/OS Version: Win 11 64-bit
- Mini PC Asus PN63
- CPU: Intel i5-1135G7
- GPU; Intel XE Iris 
- RAM: 8GB

- Source Version: 1.17.3
- Unity Version: 2022.3.11f.1

**Comment by asus4** [comment]
Sorry for the late reply. have you installed the [Visual C++ 2019 runtime](https://onnxruntime.ai/docs/install/) in the device? I don't have the same environment, but I needed to install Visual C++ when I tried it on my new Windows.
