### ISSUE TITLE
在IOS端使用CoreML来进行推理，会造成内存暴增导致应用被关闭

### ISSUE THREAD

**Issue by 493226363** [asus4/onnxruntime-unity#31]
**Environment (please complete the following information):**
 - OS/OS Version: [e.g. iOS 11.0/Andoroid 8.1/macOS 10.15.6]
 - Source Version: [e.g. master/v2.2.0]
 - Unity Version: [e.g. Unity 2019.4.5.f1]

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem and error logs here.

**Comment by asus4** [comment]
@493226363  Please fill in all required information to reproduce it.
